# Copyright (c) 2026 Fabrizio Salmi <fabrizio.salmi@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only
# NIS2 Compliance Platform — https://github.com/fabriziosalmi/messages
"""
v2.4.21 audit reports-006/007 — locale-aware labels for generated reports.

The report renderers in `app/tasks/report_tasks.py` (PDF, HTML, Markdown,
JUnit, CSV) are server-side jobs that run inside the Celery worker — they
cannot reach next-intl, which is a Next.js client-side library. Pre-v2.4.21
that meant every "NIS2 Compliance Scan Report", "Findings", "Severity",
"Executive Summary" header was hardcoded English regardless of the user's
locale, which is a poor experience for a customer-facing compliance
deliverable in IT/FR/DE/ES tenants.

Why a hand-rolled dictionary instead of Babel / gettext / a templating
engine:

  - **No new runtime dependency.** Babel pulls 45MB+ of CLDR data and a
    full datetime localizer when all we actually need is ~30 label
    translations per locale. The cost/benefit doesn't pencil out.
  - **Self-contained.** The web FE already has `messages/*.json` for its
    own i18n; mirroring that file format here would couple the worker to
    the FE bundle, which is a layering smell. Reports renderers are a
    server-side concern with their own (much smaller) string surface.
  - **Diff-friendly.** A hand-rolled dict in this file makes a "translate
    the new key in IT/FR/DE/ES" PR a 5-line change reviewers can read at
    a glance, instead of hunting through a JSON tree.

Locale fallback: anything not in the requested locale falls back to `en`.
A `None` / unknown locale string also falls back to `en`. So an exotic
locale code (e.g. `pt`, `zh`, ...) doesn't break the renderer — it just
gets the English text, which is the safest possible failure mode for a
compliance document.

Timestamps are intentionally NOT localised. We keep ISO `2026-04-28 14:30
UTC` because:
  - "UTC" is unambiguous across timezones; a Tokyo team reading the
    report knows exactly what the timestamp refers to.
  - Compliance auditors often correlate report timestamps with logs from
    other tools (Splunk, ELK, cloud audit trails) which all standardise
    on UTC ISO. Forcing those readers to mentally convert "28 aprile alle
    14:30" back into ISO is worse than the original problem.
  - User-timezone localisation would require a new `User.timezone` field;
    out of scope.

The audit (reports-008) was specifically about UTC being confusing to a
Tokyo team. We address that by keeping the explicit `UTC` suffix on every
timestamp and translating only the surrounding noun phrase (`Date`,
`Generated by`).
"""

from __future__ import annotations

# Canonical (English) keys → per-locale translations.
#
# Adding a new key:
#   1. Add it to the `en` block (the canonical fallback).
#   2. Translate to `it`, `fr`, `de`, `es`. The unit-test
#      `test_report_i18n.py::test_all_locales_have_all_keys` will
#      hold the line — a missing key in any locale fails the suite.
LABELS: dict[str, dict[str, str]] = {
    "en": {
        # Document chrome
        "report_title": "NIS2 Compliance Scan Report",
        "report_title_h1": "NIS2 Compliance Report",
        "html_title_prefix": "NIS2 Report",
        "footer_generated_by": "Generated by NIS2 Compliance Platform",
        "footer_ref": "Ref: NIS2 Directive (EU) 2022/2555, D.Lgs 138/2024",
        "generated_by_md": "Generated by NIS2 Compliance Platform",
        # Header fields (used in MD + HTML)
        "field_scan": "Scan",
        "field_date": "Date",
        "field_score": "Score",
        "field_duration": "Duration",
        "score_label": "Compliance Score",
        # Summary section
        "summary": "Summary",
        "metric": "Metric",
        "value": "Value",
        "hosts_scanned": "Hosts Scanned",
        "hosts_active": "Hosts Active",
        "executive_summary": "Executive Summary",
        # Severity buckets (used both in stat cards + MD legend)
        "critical": "Critical",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        # Findings table headers
        "findings": "Findings",
        "h_severity": "Severity",
        "h_category": "Category",
        "h_finding": "Finding",
        "h_target": "Target",
        "h_remediation": "Remediation",
        "h_cvss_score": "CVSS Score",
        "h_cvss_vector": "CVSS Vector",
        "h_compliance_article": "Compliance Article",
        "h_status": "Status",
        # Assets section
        "assets": "Assets",
        "h_ip": "IP",
        "h_host_state": "Status",
        "h_open_ports": "Open Ports",
        "host_active": "Active",
        "host_inactive": "Inactive",
        "no_open_ports": "None",
        # N/A / fallback
        "not_available": "N/A",
        "not_applicable": "-",
    },
    "it": {
        "report_title": "Report di Conformità NIS2",
        "report_title_h1": "Report di Conformità NIS2",
        "html_title_prefix": "Report NIS2",
        "footer_generated_by": "Generato da NIS2 Compliance Platform",
        "footer_ref": "Rif: Direttiva NIS2 (UE) 2022/2555, D.Lgs 138/2024",
        "generated_by_md": "Generato da NIS2 Compliance Platform",
        "field_scan": "Scansione",
        "field_date": "Data",
        "field_score": "Punteggio",
        "field_duration": "Durata",
        "score_label": "Punteggio di Conformità",
        "summary": "Riepilogo",
        "metric": "Metrica",
        "value": "Valore",
        "hosts_scanned": "Host Analizzati",
        "hosts_active": "Host Attivi",
        "executive_summary": "Riepilogo Esecutivo",
        "critical": "Critico",
        "high": "Alto",
        "medium": "Medio",
        "low": "Basso",
        "findings": "Risultati",
        "h_severity": "Severità",
        "h_category": "Categoria",
        "h_finding": "Risultato",
        "h_target": "Target",
        "h_remediation": "Rimedio",
        "h_cvss_score": "Punteggio CVSS",
        "h_cvss_vector": "Vettore CVSS",
        "h_compliance_article": "Articolo Normativo",
        "h_status": "Stato",
        "assets": "Asset",
        "h_ip": "IP",
        "h_host_state": "Stato",
        "h_open_ports": "Porte Aperte",
        "host_active": "Attivo",
        "host_inactive": "Inattivo",
        "no_open_ports": "Nessuna",
        "not_available": "N/D",
        "not_applicable": "-",
    },
    "fr": {
        "report_title": "Rapport de Conformité NIS2",
        "report_title_h1": "Rapport de Conformité NIS2",
        "html_title_prefix": "Rapport NIS2",
        "footer_generated_by": "Généré par NIS2 Compliance Platform",
        "footer_ref": "Réf : Directive NIS2 (UE) 2022/2555, D.Lgs 138/2024",
        "generated_by_md": "Généré par NIS2 Compliance Platform",
        "field_scan": "Analyse",
        "field_date": "Date",
        "field_score": "Score",
        "field_duration": "Durée",
        "score_label": "Score de Conformité",
        "summary": "Résumé",
        "metric": "Indicateur",
        "value": "Valeur",
        "hosts_scanned": "Hôtes Analysés",
        "hosts_active": "Hôtes Actifs",
        "executive_summary": "Résumé Exécutif",
        "critical": "Critique",
        "high": "Élevée",
        "medium": "Moyenne",
        "low": "Faible",
        "findings": "Découvertes",
        "h_severity": "Sévérité",
        "h_category": "Catégorie",
        "h_finding": "Découverte",
        "h_target": "Cible",
        "h_remediation": "Remédiation",
        "h_cvss_score": "Score CVSS",
        "h_cvss_vector": "Vecteur CVSS",
        "h_compliance_article": "Article de Conformité",
        "h_status": "Statut",
        "assets": "Actifs",
        "h_ip": "IP",
        "h_host_state": "État",
        "h_open_ports": "Ports Ouverts",
        "host_active": "Actif",
        "host_inactive": "Inactif",
        "no_open_ports": "Aucun",
        "not_available": "N/D",
        "not_applicable": "-",
    },
    "de": {
        "report_title": "NIS2-Konformitätsbericht",
        "report_title_h1": "NIS2-Konformitätsbericht",
        "html_title_prefix": "NIS2-Bericht",
        "footer_generated_by": "Erstellt von NIS2 Compliance Platform",
        "footer_ref": "Ref.: NIS2-Richtlinie (EU) 2022/2555, D.Lgs 138/2024",
        "generated_by_md": "Erstellt von NIS2 Compliance Platform",
        "field_scan": "Scan",
        "field_date": "Datum",
        "field_score": "Bewertung",
        "field_duration": "Dauer",
        "score_label": "Konformitätsbewertung",
        "summary": "Zusammenfassung",
        "metric": "Metrik",
        "value": "Wert",
        "hosts_scanned": "Gescannte Hosts",
        "hosts_active": "Aktive Hosts",
        "executive_summary": "Management-Zusammenfassung",
        "critical": "Kritisch",
        "high": "Hoch",
        "medium": "Mittel",
        "low": "Niedrig",
        "findings": "Ergebnisse",
        "h_severity": "Schweregrad",
        "h_category": "Kategorie",
        "h_finding": "Ergebnis",
        "h_target": "Ziel",
        "h_remediation": "Behebung",
        "h_cvss_score": "CVSS-Bewertung",
        "h_cvss_vector": "CVSS-Vektor",
        "h_compliance_article": "Konformitätsartikel",
        "h_status": "Status",
        "assets": "Assets",
        "h_ip": "IP",
        "h_host_state": "Status",
        "h_open_ports": "Offene Ports",
        "host_active": "Aktiv",
        "host_inactive": "Inaktiv",
        "no_open_ports": "Keine",
        "not_available": "N/V",
        "not_applicable": "-",
    },
    "es": {
        "report_title": "Informe de Cumplimiento NIS2",
        "report_title_h1": "Informe de Cumplimiento NIS2",
        "html_title_prefix": "Informe NIS2",
        "footer_generated_by": "Generado por NIS2 Compliance Platform",
        "footer_ref": "Ref.: Directiva NIS2 (UE) 2022/2555, D.Lgs 138/2024",
        "generated_by_md": "Generado por NIS2 Compliance Platform",
        "field_scan": "Escaneo",
        "field_date": "Fecha",
        "field_score": "Puntuación",
        "field_duration": "Duración",
        "score_label": "Puntuación de Cumplimiento",
        "summary": "Resumen",
        "metric": "Métrica",
        "value": "Valor",
        "hosts_scanned": "Hosts Analizados",
        "hosts_active": "Hosts Activos",
        "executive_summary": "Resumen Ejecutivo",
        "critical": "Crítico",
        "high": "Alto",
        "medium": "Medio",
        "low": "Bajo",
        "findings": "Hallazgos",
        "h_severity": "Severidad",
        "h_category": "Categoría",
        "h_finding": "Hallazgo",
        "h_target": "Objetivo",
        "h_remediation": "Remediación",
        "h_cvss_score": "Puntuación CVSS",
        "h_cvss_vector": "Vector CVSS",
        "h_compliance_article": "Artículo de Cumplimiento",
        "h_status": "Estado",
        "assets": "Activos",
        "h_ip": "IP",
        "h_host_state": "Estado",
        "h_open_ports": "Puertos Abiertos",
        "host_active": "Activo",
        "host_inactive": "Inactivo",
        "no_open_ports": "Ninguno",
        "not_available": "N/D",
        "not_applicable": "-",
    },
}

SUPPORTED_LOCALES = frozenset(LABELS.keys())
DEFAULT_LOCALE = "en"


def normalize_locale(locale: str | None) -> str:
    """Map a user-stored locale string onto a key in `LABELS`.

    Accepts:
      - the canonical 2-letter codes we ship (en/it/fr/de/es)
      - regional variants (`en-US`, `it-IT`, `pt-BR`, ...) — strip the
        regional suffix and try the language base
      - None / unknown → fall back to en

    The User model currently stores 2-letter codes from the FE picker,
    so the regional-variant branch is defensive against future
    expansion (e.g. an /auth/me PATCH that accepts `pt-BR`).
    """
    if not locale:
        return DEFAULT_LOCALE
    code = locale.lower().split("-", 1)[0].split("_", 1)[0]
    return code if code in SUPPORTED_LOCALES else DEFAULT_LOCALE


def t(locale: str | None, key: str) -> str:
    """Translate `key` for the given `locale`.

    Falls back to English if either:
      - the locale is not supported (defensive — see `normalize_locale`),
      - the key is missing in the requested locale (typo / new key
        without translation; the unit tests catch these but we belt-
        and-braces it at runtime so a misspelling doesn't crash a
        report job).

    A truly unknown key (not present even in `en`) returns the key
    itself so the report still renders — the missing label shows up
    as a literal placeholder which makes the bug obvious to whoever
    reviews the document.
    """
    locale_key = normalize_locale(locale)
    bundle = LABELS.get(locale_key, LABELS[DEFAULT_LOCALE])
    if key in bundle:
        return bundle[key]
    return LABELS[DEFAULT_LOCALE].get(key, key)
