"use client"

import { useMemo } from "react"

/**
 * Allowlist-based HTML sanitizer for trusted server-generated HTML.
 *
 * Security rationale (audit fix for stored XSS via dangerouslySetInnerHTML):
 * The executive_summary field is generated by the scanner's SummaryGenerator
 * as HTML containing <div>, <strong>, <ul>, <li>, etc.  The raw HTML is
 * stored in the DB and must be rendered in the browser — but NOT via
 * dangerouslySetInnerHTML, which would execute any injected <script>,
 * event handlers (onerror, onload), or javascript: URIs.
 *
 * This component parses the HTML string with the browser's DOMParser,
 * walks the resulting tree, and keeps ONLY the tags, attributes, and
 * URI schemes that appear in the allowlists below.  Everything else
 * is stripped (tags become their text content; attributes are removed).
 *
 * Zero external dependencies — uses only the Web Platform's DOMParser API.
 */

// Tags the SummaryGenerator actually emits + harmless formatting tags.
const ALLOWED_TAGS = new Set([
  "div", "span", "p", "br",
  "strong", "b", "em", "i", "u",
  "ul", "ol", "li",
  "a",
  "h1", "h2", "h3", "h4", "h5", "h6",
])

// Attributes we keep.  `style` is allowed because the summary uses
// inline colors for severity badges; `class` for Tailwind/CSS classes.
// `href` is allowed only on <a> with scheme checks below.
const ALLOWED_ATTRS = new Set(["style", "class", "href"])

// URI schemes allowed in href.  Blocks javascript:, data:, vbscript:, etc.
const SAFE_HREF_RE = /^https?:\/\//i

function sanitizeNode(node: Node, doc: Document): Node | null {
  if (node.nodeType === Node.TEXT_NODE) {
    return doc.createTextNode(node.textContent ?? "")
  }

  if (node.nodeType !== Node.ELEMENT_NODE) {
    return null // strip comments, processing instructions, etc.
  }

  const el = node as Element
  const tagName = el.tagName.toLowerCase()

  if (!ALLOWED_TAGS.has(tagName)) {
    // Unwrap: keep children but drop the tag itself.
    const fragment = doc.createDocumentFragment()
    for (const child of Array.from(el.childNodes)) {
      const clean = sanitizeNode(child, doc)
      if (clean) fragment.appendChild(clean)
    }
    return fragment
  }

  const cleanEl = doc.createElement(tagName)

  // Copy only allowed attributes.
  for (const attr of Array.from(el.attributes)) {
    const name = attr.name.toLowerCase()
    if (!ALLOWED_ATTRS.has(name)) continue

    // href: block dangerous schemes.
    if (name === "href") {
      if (!SAFE_HREF_RE.test(attr.value.trim())) continue
    }

    cleanEl.setAttribute(name, attr.value)
  }

  // Recurse into children.
  for (const child of Array.from(el.childNodes)) {
    const clean = sanitizeNode(child, doc)
    if (clean) cleanEl.appendChild(clean)
  }

  return cleanEl
}

function sanitizeHtml(dirty: string): string {
  if (typeof window === "undefined") {
    // SSR fallback: strip ALL tags for safety (no DOMParser available).
    return dirty.replace(/<[^>]*>/g, "")
  }

  const parser = new DOMParser()
  const parsed = parser.parseFromString(dirty, "text/html")
  const doc = document.implementation.createHTMLDocument("")
  const container = doc.createElement("div")

  for (const child of Array.from(parsed.body.childNodes)) {
    const clean = sanitizeNode(child, doc)
    if (clean) container.appendChild(clean)
  }

  return container.innerHTML
}

interface SafeHtmlProps {
  html: string
  className?: string
}

/**
 * Renders server-generated HTML through an allowlist sanitizer.
 *
 * Usage:
 *   <SafeHtml html={scan.executive_summary} className="text-sm" />
 *
 * Instead of:
 *   <div dangerouslySetInnerHTML={{ __html: scan.executive_summary }} />
 */
export function SafeHtml({ html, className }: SafeHtmlProps) {
  const clean = useMemo(() => sanitizeHtml(html), [html])

  return (
    <div
      className={className}
      dangerouslySetInnerHTML={{ __html: clean }}
    />
  )
}
